Iter13
rasha108bik/tiny_url pull request #13
Opened 2023-01-13 14:01 UTC by rasha108bik

2023-01-18 00:32 UTC, capsulated requested changes
Обязательно убрать всю логику цнициализации хранилки из `cmd` - все эти проверки должны происходить в конструкторе хранилки. Также, конструктор для хранилки должен быть один, но возвращать нужную реализацию в зависимости от конфига.

Всё написал в коментах

2023-01-18 00:32 UTC, capsulated commented on cmd/shortener/main.go
> +	// TODO after delete and change pgcon
todo оставлять в PR нельзя)

2023-01-18 00:32 UTC, capsulated commented on cmd/shortener/main.go
> +	pg, err := pgDB.New(cfg.DatabaseDSN)
Всё, что связано с Postgres нужно "убрать" в пакет, который реализует работу с БД. В cmd это не нужно реализовывать

2023-01-18 00:32 UTC, capsulated commented on cmd/shortener/main.go
>  	serv := server.NewServer(h)
Если есть конструктор для сервера, тогда и `cfg.ServerAddress` и экземпляр роутера нужно передать в конструктор сервера, в нём создать "обёртку" для `ListenAndServe`, либо "расширить" сервер своими полями с помощью встраивания. То есть, в итоге вызывать `serv.ListenAndServe()` без параметров, к примеру. Либо, не создавать свой экземпляр с помощью `NewServer`

2023-01-18 00:32 UTC, capsulated commented on config/config.go
>  	if fileStoragePath != "" {
Условный оператор лишний, дефолтное значения для строки какое?

2023-01-18 00:32 UTC, capsulated commented on config/config.go
> +	if databaseDSN != "" {
Так же

2023-01-18 00:32 UTC, capsulated commented on internal/server/handlers/handlers.go
> +	memDB       storage.Storager
Два поля не должно быть. В идеале: одно, которое реализует либо один вариант записи, либо другой. А имя одно: `store`, `storage`, `repository` и тп. А как оно записывает (в память, базу данных или файл) - это должно определяться и реализовываться внутри пакета, в зависимости от конфига.

2023-01-18 00:32 UTC, capsulated commented on internal/server/handlers/handlers.go
> +	if h.pgcon {
очень много if/else, нужно упростить максимально, чтобы условных "ветвлений" было минимум по возможности

2023-01-18 00:32 UTC, capsulated commented on internal/server/handlers/handlers.go
> +	if h.pgcon {
Так же, if/else очень много, что перегружает логику

2023-01-18 00:32 UTC, capsulated commented on internal/server/handlers/handlers.go
> +	if err != nil {
Так же, можно упростить

2023-01-18 00:32 UTC, capsulated commented on internal/server/handlers/handlers.go
> +	if h.pgcon {
Реализация использования БД с помощью флага  - плохая идея. Здесь должен вызываться метод хранилки при любом конфиге, а что там используется (память или БД) уже должно происходить внутри хранилки

2023-01-18 00:32 UTC, capsulated commented on internal/storage/file/filestorage.go
>  type Event struct {
Это я пропустил в прошлом ревью? А для чего целая структура? Мне кажется, что она лишняя. Можно сразу стрингу передавать, не?

2023-01-18 00:32 UTC, capsulated commented on internal/storage/file/filestorage.go
> +func (f *fileStorage) GetAllURLs() (map[string]string, error) {
Плохо реализовывать методы, которые есть в интерфейсе, но которые не нужны по логике. Нужно разделить интерфейс на несколько более мелких. interface segregation principle из SOLID

2023-01-18 00:32 UTC, capsulated commented on internal/storage/postgres/postgres.go
> +func New(dns string) (*postgres, error) {
параметр - "connString" почти везде именуется

2023-01-18 00:32 UTC, capsulated commented on internal/storage/postgres/postgres.go
> +func New(dns string) (*postgres, error) {
И `NewPostgres` имя конструктора по [эффектив го](https://github.com/Konstantin8105/Effective_Go_RU)

2023-01-20 05:59 UTC, rasha108bik commented on config/config.go
>  	if fileStoragePath != "" {
тут есть дефолтное значение

2023-01-20 05:59 UTC, rasha108bik commented on config/config.go
> +	if databaseDSN != "" {
тут да

2023-01-20 05:59 UTC, rasha108bik commented on internal/server/handlers/handlers.go
> +	if h.pgcon {
+

2023-01-20 06:01 UTC, rasha108bik commented on internal/storage/file/filestorage.go
>  type Event struct {
done

2023-01-20 06:01 UTC, rasha108bik commented on internal/storage/file/filestorage.go
>  type Event struct {
+

2023-01-20 06:05 UTC, rasha108bik commented on internal/storage/postgres/postgres.go
> +func New(dns string) (*postgres, error) {
done

2023-01-20 06:28 UTC, rasha108bik commented on cmd/shortener/main.go
>  	serv := server.NewServer(h)
done

2023-01-20 06:46 UTC, rasha108bik commented on internal/storage/file/filestorage.go
> +func (f *fileStorage) GetAllURLs() (map[string]string, error) {
done интересный подход с interface segregation principle из SOLID - сделал так https://levelup.gitconnected.com/practical-solid-in-golang-interface-segregation-principle-f272c2a9a270

2023-01-23 06:05 UTC, rasha108bik commented on internal/server/handlers/handlers.go
> +	if h.pgcon {
done

2023-01-23 06:09 UTC, rasha108bik commented on cmd/shortener/main.go
> +	// TODO after delete and change pgcon
done

2023-01-23 06:10 UTC, rasha108bik commented on internal/server/handlers/handlers.go
> +	if err != nil {
done

2023-01-26 21:07 UTC, bambruysk requested changes
Нужно защитить мапу и убрать комментированный код. Сдкелдать тесты более структурными

2023-01-26 21:07 UTC, bambruysk commented on internal/server/handlers/handlers.go
> +	// if shrURL != "" {
Закомментированный код удалить

2023-01-26 21:07 UTC, bambruysk commented on internal/server/handlers/handlers.go
> +	for _, v := range m {
Это все долэно быть в слое бизнес-логики

2023-01-26 21:07 UTC, bambruysk commented on internal/server/handlers/handlers_test.go
> +	t.Run("save StatusConflict", func(t *testing.T) {
лучше разбить на отдельные тесты -  если хочется что0то общее для низх то посмотрите на testify/suite

2023-01-26 21:07 UTC, bambruysk commented on internal/storager/memdb/storage.go
> +	f.Locations[shortURL] = originalURL
Записть в мапу не защищена мьютексом

2023-01-26 21:07 UTC, bambruysk commented on internal/storager/memdb/storage.go
> +	Locations map[string]string
Зачем это поле экспортируемое

2023-01-26 21:07 UTC, bambruysk commented on internal/storager/postgres/postgres.go
> +	Psg *sqlx.DB
зачем оно экспортируемое?

2023-01-27 05:20 UTC, rasha108bik commented on internal/storager/postgres/postgres.go
> +	Psg *sqlx.DB
done

2023-01-27 05:20 UTC, rasha108bik commented on internal/storager/memdb/storage.go
> +	Locations map[string]string
done

2023-01-27 05:20 UTC, rasha108bik commented on internal/storager/memdb/storage.go
> +	f.Locations[shortURL] = originalURL
done

2023-01-27 05:20 UTC, rasha108bik commented on internal/server/handlers/handlers_test.go
> +	t.Run("save StatusConflict", func(t *testing.T) {
done

2023-01-27 05:20 UTC, rasha108bik commented on internal/server/handlers/handlers.go
> +	// if shrURL != "" {
done

2023-01-27 05:22 UTC, rasha108bik commented on internal/server/handlers/handlers.go
> +	for _, v := range m {
можешь показать, как это выглядит ? Я по сути всю бизнесс логику в handlers делаю, но кажется это не совсем верно, но в рамках небольшого сервиса возможно и норм

2023-01-27 15:13 UTC, bambruysk commented on internal/server/handlers/handlers.go
> +	for _, v := range m {
https://github.com/bxcodec/go-clean-arch 
маленькие сервисы имеют привычку расти - так что раздлеление не лишнее. Кроме того, так как проект учебный - надо освоить эту концепцию

2023-01-29 08:13 UTC, merged