Iter14
rasha108bik/tiny_url pull request #14
Opened 2023-01-24 06:06 UTC by rasha108bik

2023-01-27 20:41 UTC, bambruysk approved these changes

2023-01-30 09:49 UTC, Bazys requested changes
добавить ctx во все функции `Storager interface`
для постгрес и файлов это использовать реально, для памяти, можно просто сделать заглушки

2023-01-30 09:49 UTC, Bazys commented on internal/storager/postgres/postgres.go
> +	return nil
смысл возвращать всегда nil?
может просто ничего не возвращать?
или ты пропустил return в ифах

2023-01-30 09:49 UTC, Bazys commented on internal/storager/postgres/postgres.go
> +func NewPostgres(connString string) (*psg, error) {
публичная функция возвращает непубличную переменную?
может нет смысла в публичной функции?

2023-01-30 09:49 UTC, Bazys commented on config/config.go
>  func init() {
не рекомендую использование init()
я понимаю что в учебных примерах так дано. Но желательно заглянуть глубже, посмотреть как реализовано в серьезных проектах, например в том же GitHub CLI

2023-01-30 09:49 UTC, Bazys commented on internal/server/handlers/delete.go
> +			ctx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
а что тебе здесь мешает использовать r.Context() вместо context.Background()?
в принципе, использование context.Background() вне main не правильная практика.
в крайнем случае ставь context.TODO() - суть не меняется, но ты будешь помнить что эта часть к доработке

2023-01-30 09:49 UTC, Bazys commented on internal/server/handlers/handlers.go
> +	str storager.Storager
str - так обычно всё таки сокращают string. я бы переименовал, что бы не вводить в заблуждение тех кто читает код.

2023-01-30 09:49 UTC, Bazys commented on internal/storager/postgres/postgres.go
> +func (p *psg) DeleteURLsbyShortURL(ctx context.Context, shortURLs string) error {
а зачем здесь контекст, если ты его не используешь?

2023-01-30 09:49 UTC, Bazys commented on internal/storager/postgres/postgres.go
> +	// tx, err := p.psg.Beginx()
закоментированый код при PR в мастер - некрасиво (ты не уверен в своих действиях)

2023-01-31 05:30 UTC, rasha108bik commented on internal/server/handlers/delete.go
> +			ctx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
done

2023-01-31 05:31 UTC, rasha108bik commented on internal/server/handlers/handlers.go
> +	str storager.Storager
done

2023-01-31 05:33 UTC, rasha108bik commented on internal/storager/postgres/postgres.go
> +func (p *psg) DeleteURLsbyShortURL(ctx context.Context, shortURLs string) error {
done

2023-01-31 05:33 UTC, rasha108bik commented on internal/storager/postgres/postgres.go
> +	// tx, err := p.psg.Beginx()
done

2023-01-31 05:34 UTC, rasha108bik commented on internal/storager/postgres/postgres.go
> +	return nil
done, вернул error

2023-01-31 05:35 UTC, rasha108bik commented on internal/storager/postgres/postgres.go
> +func NewPostgres(connString string) (*psg, error) {
done, есть смысл вернул Psg

2023-01-31 06:41 UTC, rasha108bik commented on config/config.go
>  func init() {
не нашел, если есть пример скинь пжл

2023-01-31 07:21 UTC, Bazys approved these changes
https://github.com/cli/cli/blob/trunk/cmd/gen-docs/main.go#L23

2023-01-31 07:21 UTC, Bazys commented on internal/storager/postgres/postgres.go
> +		log.Printf("postgres.WithInstance: %v\n", err)
а здесь?

2023-01-31 07:21 UTC, Bazys commented on internal/storager/postgres/postgres.go
> +	psg *sqlx.DB
я бы просто назвал `db`

2023-01-31 07:21 UTC, Bazys commented on internal/storager/file/filestorage.go
> +	data, err := json.Marshal(
как раз будет работа для второй части
можно будет завернуть работу с файлами в горутину и контролировать эту горутину как раз этим контекстом.
Заодно и будет тема для профилирования.

2023-01-31 07:21 UTC, Bazys commented on internal/storager/memdb/storage.go
> +func (m *memDB) StoreURL(ctx context.Context, originalURL string, shortURL string) error {
```suggestion
func (m *memDB) StoreURL(_ context.Context, originalURL string, shortURL string) error {
```
что бы линтеры не ругались

2023-01-31 10:42 UTC, rasha108bik commented on internal/storager/memdb/storage.go
> +func (m *memDB) StoreURL(ctx context.Context, originalURL string, shortURL string) error {
done

2023-01-31 10:45 UTC, rasha108bik commented on internal/storager/postgres/postgres.go
> +	psg *sqlx.DB
done

2023-01-31 11:25 UTC, merged