Iter3
rasha108bik/tiny_url pull request #3
Opened 2022-11-22 15:17 UTC by rasha108bik

iter3

2022-11-25 22:35 UTC, capsulated requested changes
Очень быстро)) Это круто!

Замечания написал в комментах

2022-11-25 22:35 UTC, capsulated commented on cmd/shortener/main.go
> +	r.Use(middleware.RequestID)
Для чего добавлены **middleware**? В первом спринте пока ещё не было заданий по ним, вроде бы. Если добавлять, то нужно точно определиться, нужны ли они. Если есть какая-то идея - то пиши ответом на этот комент

2022-11-25 22:35 UTC, capsulated commented on cmd/shortener/main.go
> +	// A good base middleware stack
Комментарии писать не очень хорошая практика (если это не **godoc**). Лучше именовать пакеты/структуры/функции так, чтобы комментарий даже не понадобился. То есть, что-то такое, как комментарий, но короче. 

И с примеров используемого пакета их лучше не копировать)

2022-11-25 22:35 UTC, capsulated commented on cmd/shortener/main.go
> +	db := storage.New()
Go community предлагает именовать комнтрукторы `New<ИмяОбъекта>()`
https://go.dev/doc/effective_go#composite_literals

В процессе обучения будем придерживаться правил:
https://go.dev/doc/effective_go
https://github.com/golang/go/wiki/CodeReviewComments

И более общие, родительские разделы:
https://go.dev/doc/
https://github.com/golang/go/wiki/

2022-11-25 22:35 UTC, capsulated commented on cmd/shortener/main.go
> +	r.MethodNotAllowed(handlers.URLErrorHandler)
За что ты оторвал `URLErrorHandler()` от своих собратьев `GetHandler()` `PostHandler()`? 😅

По неймингу:
- в имени можно и не добавлять постфикс `Handler`, так как Handlers (я бы в единственном числе называл пакеты, для удобного чтения при написании) есть в названии пакета;
- обобщенные имена методов - плохая практика, лучше называть их по контексту того, что они делают, с глаголом
- использовать способ реализации в имени (http метод в данном случае) также, не оч хорошая практика; имена должны ничего не говорить о способах реализации, а только о том, что метод делает

Пример:
```go
Handler.CreateShortLink()
Handler.ShortLinkRedirect()
Handler.ErrorMethodNotAllowed()
Handler.ErrorNotFound()
```

2022-11-25 22:35 UTC, capsulated commented on internal/server/handlers/handlers.go
> +func (h *handler) PostHandler() http.HandlerFunc {
В `chi` хендлер можно описать как функцию, которая не возвращает значения `func(w http.ResponseWriter, r *http.Request)`, либо возвращающая тип `HandlerFunc`, который является функцией.

В нашем случае используется обертка `HandlerFunc` с возвращением функции. Почему именно такой способ?

2022-11-25 22:35 UTC, capsulated commented on internal/server/handlers/handlers.go
> +		makeResponse(w, "application/json", []byte("http://127.0.0.1:8080/"+res), http.StatusCreated)
Единственный раз вызванная функция. Лучше избавляться от таких конструкций, если они не повторяются. Когда повторяется абсолютно одинаковый код - тогда стоит думать о создании функции/метода

И для злосчастного `if err != nil ...` лучше обертки не изобретать - также усложняет чтение кода

2022-11-25 22:35 UTC, capsulated commented on internal/storage/storage.go
> +	Save(longURL string) (string, error)
Чуть-чуть подробнее бы: в имени уточнить, что именно сохраняется

К примеру:
```go
StoreUrl()
GetUrlShortId()
```

2022-11-25 22:35 UTC, capsulated commented on internal/storage/storage.go
> +	s.Locations[newID] = longURL
Мы этого ещё не проходили, но как теорема (исправлять не нужно, но запомнить обязательно!), вернёмся к этому в следующих уроках - нужно осторожно работать с типами данных при параллельной работе. Веб-сервер работает параллельно: могут одновременно несколько пользователей обратиться по url. Называется "потокобезопасность" - очень важная история, нужно запомнить, но рассмотрим позже

2022-11-28 10:40 UTC, rasha108bik commented on cmd/shortener/main.go
> +	r.Use(middleware.RequestID)
заюзал middleware из пакета chi для логированию request, а также Recoverer для того, чтобы восстанавливать запрос, если будет паника

	r.Use(middleware.RealIP) - уберу

2022-11-28 10:41 UTC, rasha108bik commented on cmd/shortener/main.go
> +	// A good base middleware stack
ok

2022-11-28 10:42 UTC, rasha108bik commented on cmd/shortener/main.go
> +	db := storage.New()
исправлю

2022-11-28 10:51 UTC, rasha108bik commented on cmd/shortener/main.go
> +	db := storage.New()
исправил

2022-11-28 10:51 UTC, rasha108bik commented on cmd/shortener/main.go
> +	r.MethodNotAllowed(handlers.URLErrorHandler)
исправил

2022-11-28 10:53 UTC, rasha108bik commented on internal/server/handlers/handlers.go
> +		makeResponse(w, "application/json", []byte("http://127.0.0.1:8080/"+res), http.StatusCreated)
согласен, исправил

2022-11-28 10:59 UTC, rasha108bik commented on internal/storage/storage.go
> +	Save(longURL string) (string, error)
исправил, тока URL вроде нужно

2022-11-28 11:27 UTC, rasha108bik commented on internal/server/handlers/handlers.go
> +func (h *handler) PostHandler() http.HandlerFunc {
я не правильно сделал, если возвращать, как у меня, то это для middlwear как раз

Переделал

2022-11-30 23:06 UTC, capsulated commented on cmd/shortener/main.go
> +	r.Use(middleware.RequestID)
Ну да, это в примере использования chi, но оно лишнее сейчас. В PR ничего лишнего и "на будущее" лучше не добавлять - это плохая практика

2022-11-30 23:08 UTC, capsulated commented on internal/server/handlers/handlers.go
> +func (h *handler) PostHandler() http.HandlerFunc {
Оно не то, чтобы неправильно, скорее, лишнее. Работать будет всё также, но просто код усложняет. Хотя бываю случаи, когда такое нужно

2022-11-30 23:09 UTC, capsulated commented on internal/storage/storage.go
> +	Save(longURL string) (string, error)
А это как нравится. Главное, чтобы в пределах проекта было одинаково. Я наоборот пишу `Id`, `Url` и тп, это кому как нравиться больше))

2022-11-30 23:11 UTC, capsulated approved these changes
Отлично! ) Едем дальше)

2022-12-01 09:27 UTC, merged