Iter8
rasha108bik/tiny_url pull request #8
Opened 2022-12-17 11:18 UTC by rasha108bik

2022-12-20 05:15 UTC, capsulated requested changes
🤔 Сложная ситуация с consumer'ом и producer'ом. Обычно этот паттерн применяется для асинхронной отправки сообщений между сервисами/потоками и тп. В принципе, реализация, вообщем-то, рабочая: держится файл открытым на чтение и на добавление в рантайме, да?

Но, в любом случае, нужно эту реализацию скрыть под методами хранилища. Само хранилище и запись/чтение файла - это разные уровни абстракции, а в хендлере они на одном уровне, а хендлер не дожен ничего знать об этом

Стандартный подход: две разные структуры, одна работает с базой, другая с файлом. Обе реализуют один интерфейс `Storager`

В одном комменте нереально объяснить, лучше 1-1 скорее всего, чтобы сочинение не писать) Отправляй личное сообщение, договоримся о звонке

2022-12-20 05:15 UTC, capsulated commented on URLs.log
> +{"URL":"1"}
Логи, файлы с данными (url'ы в нашем случае), бинарники, значения переменных окружения, токены, ключи,  пароли и другие credentials - всё это комитить (и тем более пушить) в гит репозиторий  небезопасно

Нужно добавить в `.gitignore` необходимое, а из репозитория удалить. Для enterprise / production проектов - это пересоздавать репозиторий, так как из git истории полностью удалить проблематично, хеши всё равно остаются и можно восстановить удалённые (и даже rebase) комиты. Нужно детальнее читать доку по гиту и смотреть, как он работает детальнее, чтобы точно сказать, можно ли окончательно удалить из истории репы или нет

2022-12-20 05:15 UTC, capsulated commented on cmd/shortener/main.go
> +	serverAddress   string
Половина логики конфигурации в `cmd`, половина в пакете `config`

Лучше перенести всё, что связано с конфигом в пакет. А в `main()` только вызов конструктора, и передача указателя на экземпляр конфига:

```go
func main() {
   cfg := config.NewConfig()
   // а ещё лучше, контекст добавить
   ctx, cancel := context.Background()
   db, err := storage.NewStorage(ctx, cf) // и ошибки, если они могут быть, конечно
   if err != nil { ... }

   hdl, err := handlers.NewHandler(ctx, db)
   if err != nil { ... }

   srv := server.NewServer(ctx, ctx, hdl)
   if err != nil { ... }

   go srv.Start()
   ...

   // Завершение программы и отмена контекста
   ...
   cancel()
   ...
}
```

Контекста в задании не было)

2022-12-20 05:15 UTC, capsulated commented on cmd/shortener/main.go
> +func init() {
в конфиг

2022-12-20 05:15 UTC, capsulated commented on cmd/shortener/main.go
> +	flag.Parse()
в конфиг

2022-12-20 05:15 UTC, capsulated commented on cmd/shortener/main.go
> +	if serverAddress != "" {
и это

2022-12-20 05:15 UTC, capsulated commented on cmd/shortener/main.go
> +	app.Run(&cfg)
А зачем ещё один `cmd`?

У нас пакет `cmd` - это по факту "запускатор" приложения. Бывают кейсы, когда приложение может запускать несколько программ с одной кодовой базой - в этом случае есть логика в `cmd` + `app` 

В нашем примере - это только усложняет структуру приложение, так как у нас один экземпляр одной программы.

 Либо, если есть причина в такой реализации - буду ждать ответ-обоснование на этот комент))

2022-12-20 05:15 UTC, capsulated commented on internal/app/app.go
> +	producer, err := storagefile.NewProducer(fileName)
А почему нейминг `producer / consumer`? В принципе, по терминологии правильно, да, чтение запись в поток. Но, обычно, не используют эти термины при работе с файлами и потоками.

Пример [пакет io стандартной библиотеки go](https://cs.opensource.google/go/go/+/master:src/io/io.go)

`Read`, `Reader`, `Write`, `Writer` и тп...

2022-12-20 05:15 UTC, capsulated commented on internal/app/app.go
> +	consumer, err := storagefile.NewConsumer(fileName)
B зачем именно две структуры? Если одну сделать со всем и нужными методами?

2022-12-20 05:15 UTC, capsulated commented on internal/app/app.go
> +	r.Use(middleware.GzipHandle)
Назначение роутов убрать нужно в отдельный пакет или уже существующий (нужно подумать, как удобнее будет)

2022-12-21 06:35 UTC, rasha108bik commented on URLs.log
> +{"URL":"1"}
согласен, удалил

2022-12-21 06:36 UTC, rasha108bik commented on cmd/shortener/main.go
> +	if serverAddress != "" {
ок

2022-12-21 06:36 UTC, rasha108bik commented on cmd/shortener/main.go
> +	flag.Parse()
ок

2022-12-21 06:36 UTC, rasha108bik commented on cmd/shortener/main.go
> +func init() {
ок

2022-12-21 06:38 UTC, rasha108bik commented on cmd/shortener/main.go
> +	app.Run(&cfg)
согласен. Посмотрел проект они так сделали https://github.com/evrone/go-clean-template и типа чем меньше в main,  тем лучше говорят, но в моем случае достаточно в config вынести

2022-12-21 06:57 UTC, rasha108bik commented on internal/app/app.go
> +	producer, err := storagefile.NewProducer(fileName)
согласен, скорее для брокера сообщений

2022-12-21 07:09 UTC, rasha108bik commented on internal/app/app.go
> +	consumer, err := storagefile.NewConsumer(fileName)
Согласен. Кажется перебор

2022-12-21 08:33 UTC, rasha108bik commented on internal/app/app.go
> +	r.Use(middleware.GzipHandle)
не совсем понял зачем и как это сделать, если есть пример буду признателен

2022-12-21 08:47 UTC, rasha108bik commented on internal/app/app.go
> +	consumer, err := storagefile.NewConsumer(fileName)
ссоре, не понял, если есть пример то будет крута

2022-12-21 08:52 UTC, rasha108bik commented on URLs.log
> +{"URL":"1"}
Если есть пример будет круто! Я так вроде понял в целом, но где разместить интерфейс, и как вообще его сделать у меня же аргументы отличаются, сделать его как-то более общим

2022-12-22 19:09 UTC, capsulated commented on URLs.log
> +{"URL":"1"}
Должны быть одинаковыми аргументы, сигнатура методов полностью -  это и есть интерфейс.

Пример [тут](https://golang-blog.blogspot.com/2019/10/factory-pattern.html). В следующем спринте, скорее всего, решение задачи подталкнёт к использованию паттерна фабрика

2022-12-22 19:39 UTC, capsulated commented on cmd/shortener/main.go
> +	app.Run(&cfg)
**Evron** советую попозже применять, когда стандартный го будет уже привычен. Сейчас реализовывать их подход удвоит сложность. 

Советую только `go` разработчиков (комьюнити) пользоваться доками и практиками. А после освоения - уже все остальное (фреймворки, шаблоны, подходы и практики и тп других компаний

Про `cmd` в [описании golang project layout ](https://github.com/golang-standards/project-layout#cmd)

- [Главная](https://go.dev/doc/) дока
- [Effective Go](https://go.dev/doc/effective_go)
- [Effective Go RU](https://github.com/Konstantin8105/Effective_Go_RU)
- [CodeReviewComments ](https://github.com/golang/go/wiki/CodeReviewComments)

И две книги:
- Язык программирования Go | Керниган Брайан У., Донован Алан А. А.
- Golang для профи: работа с сетью, многопоточность, структуры данных и машинное обучение с Go | Цукалос Михалис

2022-12-22 19:57 UTC, capsulated commented on internal/app/app.go
> +	r.Use(middleware.GzipHandle)
Потому, что  в пакете `app` определение роутера происходит, который не относиться к области ответственности этого пакета. Что такое "пакет" в го есть понимание? Если коротко - то так же, как `storage` реализовать. А `app` вообще удалить можно.

Примеры все в исходниках go, самые хорошие для изучения `net/http` и `io`. Ctrl/Cmd + Click в IDE откроется исходный код. По исходникам go отлично можно изучать стиль, примеров очень много.

Если сложно - то уже только 1-1 - пиши в директ, выберем время. Я покажу всё.

2022-12-22 20:02 UTC, capsulated requested changes
Из `main()` обязательно убрать нужно инициализацию `chi` роутера - перенести куда-то, например в пакет `handler` или отдельный `router` - также, как `storage` сейчас сделан

А в cmd [только вызов коснтрукторов и запуск ](https://github.com/golang-standards/project-layout#cmd)

Скорее всего созвонится нужно 1-1, а то так не получается разобраться

2022-12-22 20:03 UTC, capsulated requested changes
Из `main()` обязательно убрать нужно инициализацию `chi` роутера - перенести куда-то, например в пакет `handler` или отдельный `router` - также, как `storage` сейчас сделан

А в cmd [только вызов коснтрукторов и запуск ](https://github.com/golang-standards/project-layout#cmd)

Скорее всего созвонится нужно 1-1, а то так не получается разобраться

2022-12-23 15:52 UTC, rasha108bik commented on cmd/shortener/main.go
> +	serverAddress   string
убрал

2022-12-23 15:53 UTC, rasha108bik commented on internal/app/app.go
> +	r.Use(middleware.GzipHandle)
app удалил

2022-12-28 01:30 UTC, capsulated approved these changes
Я дополнил коменты. 

Апрувлю, так как перед праздниками сейчас будет неудобно нам исправлениями заниматься. Минимально задача в любом случае выполнена (тесты прошли).

Но предлагаю в начале след спринта созвониться и пробежимся по тому, где желательно отредактировать и, перед выполнением след спринта, исправить. Я смогу сделать ветку, запишем все обсуждения в комментариях с небольшими примерами  (если это понадобится),  и я запушу. У тебя всё будет в "под рукой"

2022-12-28 01:30 UTC, capsulated commented on README.md
> +Using clean architecture https://github.com/evrone/go-clean-template
Далее (следующие файлы в папке binary), я бинарники не проcил удалить из репозитория? 

На всякий случай, ешё раз (если вдруг говорил): бинарники, логи, а самое критичное, конкретные конфиги (значения переменных окружения, с паролями, токенами и др credentials) - это на собесах прям сразу  'завернут' на этапе просмотра репозиториев. С начала разработки нужно учитывать, тк как полностью из гит -репозитория удалить очень сложно (хеши остаются)

2022-12-28 01:30 UTC, capsulated commented on cmd/shortener/main.go
> +	fileName := cfg.FileStoragePath
А зачем ещё одна переменная `fileName`? Есть же `cfg` объект со всеми значениями нужными. И указатель на него всем 'скармливать'. Это не то, что там прям аллокация памяти увеличивается (это по факту вообще 'дешево'), а вот чтение и поддержку код усложнит

2022-12-28 01:30 UTC, capsulated commented on cmd/shortener/main.go
> +	defer filestorage.Close()
Defer я бы не ставил для `filestorage.Close()`. Лучше непосредственно вызвать там, где необходимо. В примерах реализации `gracefullу shutdown golang` (но надо гуглить примеры, стандартного/унифицированного подхода нет, к сожалению)

2022-12-28 01:36 UTC, capsulated commented on README.md
> +Using clean architecture https://github.com/evrone/go-clean-template
А, и фалы с данными. И фалы данных из БД, тоже) И временные файлы. Всё это нельзя пушить в гит - тимлид всегда будет ругацо

2023-01-15 12:52 UTC, merged